services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sa
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    # Giới hạn tài nguyên container
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '4G'

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend
    # Giới hạn tài nguyên container
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: hatanduy123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1231
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - backend
    # Giới hạn tài nguyên container
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'

volumes:
  postgres_data:

networks:
  backend:



#docker-compose -f ./docker-compose.yml down
#docker-compose -f ./docker-compose.yml up -d

